CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price DOUBLE UNSIGNED NOT NULL,
  amount INT NOT NULL,
  seller BIGINT UNSIGNED NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  CONSTRAINT `fk_product_seller`
    FOREIGN KEY (seller) REFERENCES sellers (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);
