CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(320) NOT NULL,
  password_hash VARCHAR(32) NOT NULL,
  seller BIGINT UNSIGNED,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  CONSTRAINT `fk_seller`
    FOREIGN KEY (seller) REFERENCES sellers (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);
